// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFMQ-j8pn-5NYBfTOAdHFkSqhbm6U8nco',
    appId: '1:119887795891:web:b1c832c1ce8ceb074002c6',
    messagingSenderId: '119887795891',
    projectId: 'intention-for-today-123',
    authDomain: 'intention-for-today-123.firebaseapp.com',
    storageBucket: 'intention-for-today-123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVAQJLSIbMFnLMojUvSCpl4feB14w4PN8',
    appId: '1:119887795891:android:17b318f59a9d5aed4002c6',
    messagingSenderId: '119887795891',
    projectId: 'intention-for-today-123',
    storageBucket: 'intention-for-today-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqS2R_N1Xiizxl2BZgh-IiBq_-gT8ygck',
    appId: '1:119887795891:ios:5e22e677946b3e424002c6',
    messagingSenderId: '119887795891',
    projectId: 'intention-for-today-123',
    storageBucket: 'intention-for-today-123.appspot.com',
    iosBundleId: 'com.alexpawlowski.intentionForToday',
  );
}
